export const data = [ 
    {
        "name" : "Sony Ericsson T68i",
        "text" : "Один из самых функционально насыщенных аппаратов бизнес-класса. Современный дизайн. Широкие коммуникационные возможности.",
        "img" : "t-68.png",
        "priceUs" : "$254,1",
        "priceRu" : "7750 руб",
        "icon1" : "icon-massa",
        "weight" : "85 г",
        "icon2" : "icon-size",
        "dimensions": "100x48x20 мм",
        "icon3" : "icon-time",
        "workingHours" : "400 ч./11 ч.",
        "icon4" : "icon-accum",
        "batteryType": "Polimer",
        "icon5" : "icon-color",
        "icon6" : "icon-bluetooth",
        "icon7": "icon-gprs",
        "icon8": "icon-email",
        "icon9" : "icon-signal",
        "icon10" : "icon-dictaphone",
        "icon11" : "icon-addcamera",
        "icon12" : false,
        "banner" : true
    },
    {
        "name" : "Siemens ME45",
        "text" : "Бизнес телефон. Практически полный аналог S45i. Пыле(влаго) защитный корпус.",
        "img" : "siemens-ME-45.png",
        "priceUs" : "$144",
        "priceRu" : "4390 руб",
        "icon1" : "icon-massa",
        "weight" : "99 г",
        "icon2" : "icon-size",
        "dimensions": "109x46x21 мм",
        "icon3" : "icon-time",
        "workingHours" : "300 ч./5 ч.",
        "icon4" : "icon-accum",
        "batteryType": "Li-Ion",
        "icon5" : "icon-gprs",
        "icon6" : "icon-signal",
        "icon7": "icon-dictaphone",
        "icon8": "icon-strong",
        "icon9" : "",
        "icon10" : "",
        "icon11" : "",
        "icon12" : "",
        "banner" : true
    },
     {
        "name" : "Nokia 3310",
        "text" : "Телефон, сочетающий в себе классический дизайн и все функции, необходимые нетребовательному пользователю.",
        "img" : "nokia-3310.jpg",
        "priceUs" : "$92,5",
        "priceRu" : "2820 руб",
        "icon1" : "icon-massa",
        "weight" : "113 г",
        "icon2" : "icon-size",
        "dimensions": "113x48x22 мм",
        "icon3" : "icon-time",
        "workingHours" : "260 ч./4 ч.",
        "icon4" : "icon-accum",
        "batteryType": "Ni-Mh",
        "icon5" : false,
        "icon6" : false,
        "icon7": false,
        "icon8": false,
        "icon9" : false,
        "icon10" : false,
        "icon11" : false,
        "icon12" : false,
        "banner" : true
    },
    {
        "name" : "Samsung SGH-N500",
        "text" : "Аппарат для молодежи. Встроенная антенна, возможность отправлять и принимать картинки. Управление голосом. Мобильный интернет, игры.",
        "img" : "samsung-n500.jpg",
        "priceUs" : "$129,1",
        "priceRu" : "3940 руб",
        "icon1" : "icon-massa",
        "weight" : "95 г",
        "icon2" : "icon-size",
        "dimensions": "110x46x23 мм",
        "icon3" : "icon-time",
        "workingHours" : "90 ч./3 ч.",
        "icon4" : "icon-accum",
        "batteryType": "Li-Ion",
        "icon5" : "icon-dictaphone",
        "icon6" : false,
        "icon7": false,
        "icon8": false,
        "icon9" : false,
        "icon10" : false,
        "icon11" : false,
        "icon12" : false,
        "banner" : true
    },
    {
        "name" : "Samsung S300",
        "text" : "Самая маленькая раскладушка с 2 цветными дисплеями, громкой и разнообразной полифонией и богатыми коммуникационными возможностями.",
        "img" : "samsung-s300.jpg",
        "priceUs" : "$426,9",
        "priceRu" : "13020 руб",
        "icon1" : "icon-massa",
        "weight" : "68 г",
        "icon2" : "icon-size",
        "dimensions": "80x40x22 мм",
        "icon3" : "icon-time",
        "workingHours" : "150 ч./3 ч.",
        "icon4" : "icon-accum",
        "batteryType": "Li-Ion",
        "icon5" : "icon-polifonia",
        "icon6" : "icon-color",
        "icon7": "icon-java",
        "icon8": "icon-gprs",
        "icon9" : "icon-signal",
        "icon10" : false,
        "icon11" : false,
        "icon12" : false,
        "banner" : true
    },
    {
        "name" : "Motorola V70",
        "text" : "Оригинальный дизайн, поворотный корпус, инверсионный дисплей.",
        "img" : "moto-V-70.jpg",
        "priceUs" : "$249",
        "priceRu" : "7590 руб",
        "icon1" : "icon-massa",
        "weight" : "73 г",
        "icon2" : "icon-size",
        "dimensions": "94x38x18 мм",
        "icon3" : "icon-time",
        "workingHours" : "145 ч./3 ч.",
        "icon4" : "icon-gprs",
        "batteryType": "Li-Ion",
        "icon5" : "icon-gprs",
        "icon6" : false,
        "icon7": false,
        "icon8": false,
        "icon9" : false,
        "icon10" : false,
        "icon11" : false,
        "icon12" : false,
        "banner" : true
    },
    {
        "name" : "Nokia 8310",
        "text" : "Отдохни от разговоров со встроенным FM-приемником, подключись к WAP через GPRS, измени облик телефона сменной панелью!",
        "img" : "nokia8310.jpg",
        "priceUs" : "$273,4",
        "priceRu" : "8340 руб",
        "icon1" : "icon-massa",
        "weight" : "84 г",
        "icon2" : "icon-size",
        "dimensions": "97x43x17 мм",
        "icon3" : "icon-time",
        "workingHours" : "400 ч./4 ч.",
        "icon4" : "icon-gprs",
        "batteryType": "Li-Ion",
        "icon5" : "icon-radio",
        "icon6" : "icon-gprs",
        "icon7": "icon-signal",
        "icon8": "icon-dictaphone",
        "icon9" : false,
        "icon10" : false,
        "icon11" : false,
        "icon12" : false,
        "banner" : true
    },
    {
        "name" : "Philips Xenium 9@9",
        "text" : "Лидер по времени работы - до 550 часво в режиме ожидания. Карусельное меню с пилотным колесиком. WAP.",
        "img" : "xenium.png",
        "priceUs" : "$125",
        "priceRu" : "3840 руб",
        "icon1" : "icon-massa",
        "weight" : "95 г",
        "icon2" : "icon-size",
        "dimensions": "109x41x22 мм",
        "icon3" : "icon-time",
        "workingHours" : "550 ч./6 ч.",
        "icon4" : "icon-gprs",
        "batteryType": "Li-Ion",
        "icon5" : false,
        "icon6" : false,
        "icon7": false,
        "icon8": false,
        "icon9" : false,
        "icon10" : false,
        "icon11" : false,
        "icon12" : false,
        "banner" : true
    }
]